### ISSUE TITLE
Have you trained a segmentation model with seeds from CAM step

### ISSUE THREAD

**Issue by yaoqi-zd** [YudeWang/SSENet-pytorch#2]
Hi, May I ask if you have trained a segmentation model with seeds from CAM step. In this way, we can know how much performance the random walk process brings.

**Comment by qinwang-ai** [comment]
same concern

**Comment by GuoleiSun** [comment]
same concern

**Comment by GuoleiSun** [comment]
same question. How do you train a fully supervised segmentation model using generated pseudo ground-truth

**Comment by YudeWang** [comment]
The segmentation model training setting can be viewed here.
https://github.com/YudeWang/SEAM/issues/11#issuecomment-661676318
