### ISSUE TITLE
How to get resnet38 pretrained model for training?

### ISSUE THREAD

**Issue by baek85** [YudeWang/SSENet-pytorch#3]
Thank you for upload your work.

 I have some issue with training by myself.
you uploaded resnet38 imagenet-pretrained parameter, but that link seems not working. 
Is this link working? please check the link and if the link works, tell me how to download pretrained parameters

**Comment by YudeWang** [comment]
@baek85 
Here is an answer in that repo.
https://github.com/itijyou/ademxapp/issues/24

**Comment by baek85** [comment]
Thank you!
